
export const ADD_DELIVERY_ADDRESS_REQUEST = "ADD_DELIVERY_ADDRESS_REQUEST"
export const ADD_DELIVERY_ADDRESS_SUCCESS = "ADD_DELIVERY_ADDRESS_SUCCESS"
export const ADD_DELIVERY_ADDRESS_FAILURE = "ADD_DELIVERY_ADDRESS_FAILURE" 

export const GET_DELIVERY_ADDRESS = "GET_DELIVERY_ADDRESS" 

export const REMOVE_ADDRESS_FROM_COMMON_DATA = "REMOVE_ADDRESS_FROM_COMMON_DATA"

export const ASSIGN_DELIVERY_ADDRESSES_TO_USER = "ASSIGN_DELIVERY_ADDRESSES_TO_USER"