
export const GET_SHOES_DATA_LOADING = "GET_SHOES_DATA_LOADING"
export const GET_SHOES_DATA_SUCCESS = "GET_SHOES_DATA_SUCCESS"
export const GET_SHOES_DATA_FAILURE = "GET_SHOES_DATA_FAILURE" 
export const GET_SHOES_DATA_FOR_ADMIN = "GET_SHOES_DATA_FOR_ADMIN"

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST"
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE" 

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE"
