
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE" 

export const GET_CART_DATA = "GET_CART_DATA" 
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART"
export const MANAGE_QUANTITY = "MANAGE_QUANTITY" 

export const ASSIGN_CART_USER = "ASSIGN_CART_USER"
export const ASSIGN_USER_CART_TO_TEMPCART = "ASSIGN_USER_CART_TO_TEMPCART"
export const SETTING_USER_DELIVERY_ADDRESS = "SETTING_USER_DELIVERY_ADDRESS"
export const GET_USER_ORDER_DETAILS = "GET_USER_ORDER_DETAILS"
