
export const ADD_ORDER_DETAILS_REQUEST = "ADD_ORDER_DETAILS_REQUEST"
export const ADD_ORDER_DETAILS_SUCCESS = "ADD_ORDER_DETAILS_SUCCESS"
export const ADD_ORDER_DETAILS_FAILURE = "ADD_ORDER_DETAILS_FAILURE" 

export const GET_ORDER_DETAILS_REQUEST = "GET_ORDER_DETAILS_REQUEST"
export const GET_ORDER_DETAILS_SUCCESS = "GET_ORDER_DETAILS_SUCCESS"
export const GET_ORDER_DETAILS_FAILURE = "GET_ORDER_DETAILS_FAILURE" 

export const ASSIGN_ORDER_DETAILS_TO_USER = "ASSIGN_ORDER_DETAILS_TO_USER"
export const REMOVE_FROM_ALL_ORDERS = "REMOVE_FROM_ALL_ORDERS" 

export const UPDATE_ORDER_STATUS_BY_ADMIN = "UPDATE_ORDER_STATUS_BY_ADMIN"
