
export const GET_USERS_DATA_REQUEST = "GET_USERS_DATA_REQUEST"
export const GET_USERS_DATA_SUCCESS = "GET_USERS_DATA_SUCCESS"
export const GET_USERS_DATA_FAILURE = "GET_USERS_DATA_FAILURE" 

export const UPDATE_USER_ORDER_STATUE = "UPDATE_USER_ORDER_STATUE"