
export const GET_APP_DATA_FOR_ADMIN_REQUEST = "GET_APP_DATA_FOR_ADMIN_REQUEST";
export const GET_APP_DATA_FOR_ADMIN_SUCCESS = "GET_APP_DATA_FOR_ADMIN_SUCCESS";
export const GET_APP_DATA_FOR_ADMIN_FAILURE = "GET_APP_DATA_FOR_ADMIN_FAILURE";

export const UPDATE_PRODUCT_DATA = "UPDATE_PRODUCT_DATA";